# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Open VPN
        run: sudo apt-get install openvpn

      - name: Setup VPN config
        run: |
          echo "${{ secrets.CA_CRT }}" > ca.crt
          echo "${{ secrets.USER_CRT }}" > user.crt
          echo "${{ secrets.USER_KEY }}" > user.key
          sudo chmod 700 ca.crt
          sudo chmod 700 user.crt
          sudo chmod 700 user.key

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          cat .github/vpn/demo.pem >> ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName 10.0.133.252
            User ubuntu
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END

      - name: Connect VPN
        run: |
          sudo openvpn --config ".github/vpn/config.ovpn" --log "vpn.log" --daemon

      - name: Wait for a VPN connection
        timeout-minutes: 2
        run: |
          sudo chmod 777 vpn.log
          cat vpn.log
          ssh staging "ls -la"
          

      - name: Kill VPN connection
        if: always()
        run: |
          sudo killall openvpn 
