# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Open VPN
        run: sudo apt-get install openvpn

      - name: Setup VPN config
        run: |
          echo "${{ secrets.CA_CRT }}" > ca.crt
          echo "${{ secrets.USER_CRT }}" > user.crt
          echo "${{ secrets.USER_KEY }}" > user.key
          sudo chmod 700 ca.crt
          sudo chmod 700 user.crt
          sudo chmod 700 user.key

      - name: Connect VPN
        run: sudo openvpn --config ".github/vpn/config_2.ovpn" --log "vpn.log" --daemon

      - name: Wait for a VPN connection
        timeout-minutes: 1
        run: |
          sudo chmod 600 .github/vpn/demo.pem
          echo .github/vpn/demo.pem | tr -d '\r' | ssh-add - > /dev/null
          which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H "10.0.133.252" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          ssh ubuntu@10.0.133.252

      - name: Kill VPN connection
        if: always()
        run: |
          sudo chmod 777 vpn.log
          cat vpn.log
          sudo killall openvpn 
